### ISSUE TITLE
I/O Issues

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/octotiger#333]
I have noticed some I/O issues / oddities whilst running the v1309 scenario Dominic sent me:

- Octo-Tiger will always use the local ```./X.0.silo.data``` folder to load the scenario, even though the actual restart file (given by ```--restart_filename=/path/to/file```) and its respective X.0.silo.data folder is somewhere else. Right now, one has to remember to copy said folder into the directory from which Octo-Tiger is being run.
- The measured total time does not include the loading of the restart file
- The loading of the restart (on a single compute node) file takes longer the more cores you use to run Octo-Tiger. The level 12 v1309 file was taking 40 seconds to load with 10 cores, and 4.5 minutes with 20 cores. I assume this is because all threads read the same file? Do we need the file splitting even for loading scenarios on one node?

**Comment by diehlpk** [comment]
@dmarce1 Can you comment on these?

**Comment by dmarce1** [comment]
Gregor-

 I still need to update OctoTiger so the datadir is used for the input
file, it's not a bug just a feature not yet implemented. As far as the
timing of output goes it should print that out after reading the input
file. It's not included in the totals because for a production run the read
will take a trivial amount of time.

As for why it is taking so long with more threads I don't know. I will try
and reproduce the problem.


Dominic

**Comment by diehlpk** [comment]
@dmarce1 and @G-071 Can this issue be closed?

**Comment by diehlpk** [comment]
I will close that issue for now.
