### ISSUE TITLE
Add VTK output

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/octotiger#383]
Since SILO is not so common, it would be of great interest to add VTK as some additional library. Many codes have VTK support since this format is much more common.

**Comment by shibersag** [comment]
@diehlpk, @dmarce1, I do not completely agree that VTK is so common. I think we should use HDF5 instead. 
Most of the astrophysical hydro codes use the HDF5 format. I put below a list of some of them:
Athena++, Pluto, Enzo, FLASH, Gadget, and Arepo.

There some other hydro codes that uses HDF5 as well but are less familiar. 

I took this data from yt (a very common python package to analyze and visualize hydro data in astrophysics) page:
https://yt-project.org/doc/examining/loading_data.html
Where I just search hdf5 and found many codes using it rather than VTK which only Athena uses.

**Comment by diehlpk** [comment]
@shibersag 

```
HDF5 is not, in itself, a format.
ParaView supports a few formats based on HDF5 :

    TRUCHAS HDF5 (.h5 files)
    VERA OUT HDF5 (.h5 files)
    H5Part (.h5part files)
    ENZO AMR particles (.boundary .hierarchy files)
    Xdmf2 (.xmf files)
    Xdmf3 (.xmf files)

The most popular of these formats with ParaView is Xdmf2. It is also well documented, so I would suggest using that. Of course, that depends of the actual format of your data.
```

I think we could use any format supported by Paraview.
